### ISSUE TITLE
Rename "keyvault-secrets" to keyvault

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot#196]
Please consider renaming the Keyvault starter to `azure-keyvault-spring-boot-starter` (the sample should be renamed as well accordingly if you agree).

**Comment by yungez** [comment]
@snicoll, Azure KeyVault supports keys, secrets and certification, pls see [this link](https://docs.microsoft.com/en-us/rest/api/keyvault/about-keys--secrets-and-certificates), in this starter, we only planned to support secrets in Azure KeyVault, no plan to support keys and certificates. To avoid confusing users, name is azure-keyvault-secrets-spring-boot-starter. I'll close the issue for now. pls reopen if this issue is blocking our Spring Initializr integration. thanks a lot!

**Comment by snicoll** [comment]
If it's limited, perhaps it shouldn't be a top level entry then. I can go with that name.
