### ISSUE TITLE
0.2.1 version is not published to maven central

### ISSUE THREAD

**Issue by mariuszs** [Microsoft/azure-spring-boot#251]

**Comment by Matthew-Dong** [comment]
Greetings,

We are working on this. planned to target Milestone V0.2.1 
https://github.com/Microsoft/azure-spring-boot/milestone/2

**Comment by yungez** [comment]
@mariuszs  could you pls share more detail of the issue? any specific update you didn't find in 0.2.1? which starter are you using?

**Comment by mariuszs** [comment]
0.2.1 was released but not published to maven central 

http://repo1.maven.org/maven2/com/microsoft/azure/azure-active-directory-spring-boot-starter/0.2.1/

only older version 0.2.0 is published

http://repo1.maven.org/maven2/com/microsoft/azure/azure-active-directory-spring-boot-starter/0.2.0/

**Comment by yungez** [comment]
@mariuszs , that's expected behavior. This repo contains several spring boot starters including azure-active-directory-spring-boot-starter. In 0.2.1 version, there's update in some of the starters, like azure-documentdb-spring-boot-starter, so only that part of starters released. Since no update in azure-active-directory-spring-boot-starter, so no new release. While recently we're planning to release a new version of azure-active-directory-spring-boot-starter which contains some new update, around in 2 weeks. stay tuned.

**Comment by yungez** [comment]
@mariuszs  latest 0.2.3 version of azure-active-directory-spring-boot-starter has been released to maven repo. pls check it out and ping us if any furthur question.
