### ISSUE TITLE
Auto refresh Spring boot configuration on key vault secret udpate

### ISSUE THREAD

**Issue by swagulkarni** [microsoft/azure-spring-boot#683]
We are updating the cosmos key in Azure key vault on a regular basis after key rotation.
We are using Spring boot starter project to connect out Spring app with the key vault.

My question is, does Spring boot start send an auto refresh event on detecting change to the secret stored in the Key vault so that all Spring beans marked as @RefreshScope are also updated to use the latest secret key?

**Comment by sophiaso** [comment]
@swagulkarni The Spring Boot Starter does not send an auto refresh event, for this requirement, [this sample project](https://github.com/sophiaso/spring-cosmosdb-refresh/blob/keyvault-refresh/README.md) may help.

**Comment by swagulkarni** [comment]
@sophiaso - Are there any plans to introduce this feature in the starter kit? The sample project requires a manual step to call the refresh endpoint to re-initialize the DB config beans. 
How would it work in production environment where we have automated the key rotation step in the key vault?
Our application is running in AKS clusters. How would we call refresh for all the containers running the Spring boot app?

**Comment by sophiaso** [comment]
@swagulkarni Currently we do not have plan to introduce this auto refresh feature in starter way, about refreshing in AKS cluster containers, for now, you may need to find some way to refresh.

**Comment by swagulkarni** [comment]
@sophiaso - This seems to be a very important feature to add to the starter kit. Without this, we will have to add. One of the comments in this thread [here](https://github.com/microsoft/spring-data-cosmosdb/issues/353#issuecomment-506465099) suggests that its already added to Spring boot azure app configuration starter.

**Comment by xscript** [comment]
We didn't have customer asking about this in AKS cluster.
My intuitive idea (not validated yet) is that you can implement the auto refresh functionality in your apps.

The key concept for auto refresh is [@RefreshScope](https://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#refresh-scope), which is an important feature in Spring Cloud.
That's the reason why we don't have it in Key Vault Spring Boot Starter. Because Key Vault Spring Boot Starter is a Spring Boot project. It only depends on Spring Boot and should not depend on Spring Cloud.
Introducing `@RefreshScope` into it will mess up the dependencies and doesn't align with those official Spring Boot starters.

Below are my proposal to implement auto-refresh.
- In your Key Vault, create a key named "UPDATE_TIMESTAMP" to store the timestamp when secrets are updated in Key Vault.
- In your app, configure `azure.keyvault.refresh-interval` to a value you want. Key Vault Spring Boot Starter will periodically refresh secrets as configured by this value.
Default value is 180000 ms, which is 30 minutes.
- In your app, load the timestamp value from Key Vault with our Key Vault starter.
- In your app, create a background process to periodically check whether the timestamp is updated. If it is changed, fire a `RefreshEvent` like [here](https://github.com/microsoft/spring-cloud-azure/blob/master/spring-cloud-azure-appconfiguration-config/src/main/java/com/microsoft/azure/spring/cloud/config/AzureCloudConfigWatch.java#L126).

Things worth noting:
- Apply `@RefreshScope` as [this sample](https://github.com/sophiaso/spring-cosmosdb-refresh/blob/keyvault-refresh/src/main/java/com/example/cosmosdbrefresh/CosmosConfiguration.java)
- When rotating keys, follow [this process](https://github.com/microsoft/spring-data-cosmosdb/issues/353#issuecomment-479718917) to avoid downtime.

**Comment by swagulkarni** [comment]
@xscript @Xiaolu 

In order to fire a refresh event, do we have to implement a Spring cloud bus and have all our services running in AKS cluster react to that event?

**Comment by Incarnation-p-lee** [comment]
AFAIK, you may need to leverage spring cloud bus and message middle ware like servicebus/eventhub/kafafa/RabbitMQ. If you would like to refresh all microservice by one event.

**Comment by xscript** [comment]
@swagulkarni 
There are two approaches to fire the refresh event.
- You can publish a refresh event in each instance of your app like [here](https://github.com/microsoft/spring-cloud-azure/blob/master/spring-cloud-azure-appconfiguration-config/src/main/java/com/microsoft/azure/spring/cloud/config/AzureCloudConfigWatch.java#L125-L126) to trigger the context refresh only in the current application.
- Or you can public a refresh event directly to Spring Cloud Bus to notify all instances. Refer to docs at [here](https://cloud.spring.io/spring-cloud-bus/spring-cloud-bus.html#_bus_refresh_endpoint).

**Comment by swagulkarni** [comment]
@xscript - 

We are thinking of going with the Spring cloud bus approach. The main concern with this approach is that there is no visibility as to whether all the services consumed the event and eventually refreshed the configuration.
The only way here is to wait for 4-5 mins as mentioned [here](https://github.com/microsoft/spring-data-cosmosdb/issues/353#issuecomment-479718917) in step 3 and hope that all services configuration are refreshed.
This does not sound like a full proof way to me.
Any thoughts?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
