### ISSUE TITLE
How to reuse the same instance of Key vault client

### ISSUE THREAD

**Issue by hberrayana** [microsoft/azure-spring-boot#721]
## Environment
- Spring boot starter:
  

  - key vault spring boot starter

  
- OS Type: All
- Java version: 
  
  - 1.9

  

## Summary
I'm using pod identity to access Key Vault secrets and I want to reuse the same instance of KeyVaultClient to manage keys and perform encryption. After analyzing the code, it seems that there is no way to do it currently. Should I create the same credentials and client or there should be a way to do it more properly?

**Comment by neuqlz** [comment]
Hi:
Thanks for your feedback, We will inspect it and give you a response later.

**Comment by neuqlz** [comment]
Hi @hberrayana,
Sorry for the late response, I inspect the code, there is no way to get KeyVaultClient indeed because it has not been put into spring context. There is a workaround that you can create it by yourself. We may consider adding it to the spring context in the next release, sorry for the inconvenience.

**Comment by hberrayana** [comment]
Thanks @neuqlz I already did that but it was a duplicated code.
I'll be waiting for the fix from your side.

**Comment by neuqlz** [comment]
Hi @hberrayana,
sure, if there are any updates, we will remind you.
