### ISSUE TITLE
Custom functions in Spring Data support

### ISSUE THREAD

**Issue by zhzy0077** [Microsoft/azure-spring-boot#81]
We can create custom functions in Spring Data's Repository e.g. `List<User> findUserByFirstName(String firstName)`, which is a key feature of Spring Data. Can we implement such feature in our DocumentDB starter?

**Comment by edwingustafson** [comment]
Would it be possible to quickly implement the `USE_DECLARED_QUERY` query lookup strategy in Spring Data Azure DocumentDB, to allow us to use it in our project sooner rather than later? I volunteer to work on this if you can outline how to proceed.

https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-lookup-strategies

**Comment by yungez** [comment]
@edwingustafson, your contribution is welcomed. you could reference document here https://github.com/Microsoft/azure-spring-boot-starters/blob/master/HowToContribute.md, and send PR.

**Comment by yungez** [comment]
initial basic support at https://github.com/Microsoft/spring-data-documentdb/pull/9. will discuss spring data documentdb at that repo then.
