### ISSUE TITLE
Cannot find class com.microsoft.azure.keyvault.spring.AzureKeyVaultCredential

### ISSUE THREAD

**Issue by rossdevol** [microsoft/azure-spring-boot#822]
## Environment
- Spring boot starter:
  
  - azure-spring-boot 2.2.2
  
- OS Type: MacOS
- Java version: 
  
  - 1.8
  

## Summary

When upgrading from azure-spring-boot 2.2.1 to 2.2.2, the com.microsoft.azure.keyvault.spring.AzureKeyVaultCredential class cannot be found. It has never been marked as deprecated, and we depend on this class in our code. It appears to have been deleted [in this commit](https://github.com/microsoft/azure-spring-boot/commit/4543480ed26976dfb9eec71375855da5ed24fdc6). Deleting this class (along with several others) is not mentioned in the [release notes](https://github.com/Microsoft/azure-spring-boot/releases). I looked at other code changes in the commit, and it appears that usages of AzureKeyVaultCredential were replaced with ClientSecretCredential, but this requires the tenant ID, which we store in a key vault, which means that this is not an option for us.

## Reproduce steps

- Add dependency com.microsoft.azure:azure-spring-boot:2.2.1
- Add import com.microsoft.azure.keyvault.spring.AzureKeyVaultCredential to a class
- Upgrade azure-spring-boot to 2.2.2

## Expected Results

The import of com.microsoft.azure.keyvault.spring.AzureKeyVaultCredential should still work.

## Actual Results
Compiler error "Cannot resolve symbol 'AzureKeyVaultCredential'"

**Comment by neuqlz** [comment]
Hi @rossdevol, sorry for the late response because of the Chinese New Year Holiday.
Yep, there is a breaking change in version 2.2.2 because we update Keyvault SDK to             <artifactId>azure-security-keyvault-secrets</artifactId>. In this version, it use the new SDK (  <artifactId>azure-identity</artifactId>)  to do authentication. So AzureKeyVaultCredential has been deprecated. Sorry for the omit in Release Note, I will add this part into it.

**Comment by saragluna** [comment]
Close this issue for now.
