### ISSUE TITLE
Support for AzureCliCredential

### ISSUE THREAD

**Issue by sitase** [microsoft/azure-spring-boot#846]
## Environment
Applies to development towards all services.

## Summary
The starter kits do not (AFAIK) allow use of the local currently logged in user to authenticate to Azure services. Cf https://github.com/Azure/azure-sdk-for-java that has DefaultAzureCredential that will in turn try different mechanisms, including AzureCliCredentials.

For development purposes it would be smooth if spring boot could authenticate as the developer seamlessly when on his or her local development environment.

Cf #823

## Reproduce steps
N/A

## Expected Results
N/A

## Actual Results
N/A

**Comment by neuqlz** [comment]
Hi @sitase 
Thanks for your proposal.

Our starter kits now support three authentication ways: 
1. service principal.
2. certificate.
3. managed identity.

It indeed doesn't support "AzureCliCredential". But in my opinion, the starter kits are designed for the microservice scenario rather than the client scenario. In regards to the microservice scenario, there seems no need to use the  "AzureCliCredential" to do authentication. So we need to discuss its reasonability about adding this auth mechanism into starter kits. We will give you a response later, please stay tuned.

**Comment by sitase** [comment]
I explained myself badly. When you develop a microservice, you need to be able to run it locally to test and debug. The rights to do so should derive from the local user having a dev role for the project. I.e. the rights to access an azure service in the dev environment should be assigned to the msi of deployed microservices in the dev environment AND the members of the development team. To achieve the latter, without sharing static credentials (service principals) you need to support AzureCliCredentials.

**Comment by neuqlz** [comment]
Okay, got your point, we will discuss it and respond to you later.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
