### ISSUE TITLE
Option to set TTL on Container level using azure spring boot starter cosmos

### ISSUE THREAD

**Issue by ssrm** [microsoft/azure-spring-boot#875]
## Environment
- Spring boot starter:
  
  - cosmosdb spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.11

  

## Summary
I am using azure-cosmosdb-spring-boot-starter: 2.2.4 and looking for an option to set TTL on container level. Is there any such thing available currently? At-least I didn't find any documentation. 

If we can do that using application.properties, can someone share how we can get that? If not can we get that implemented?

**Comment by saragluna** [comment]
Thanks for reaching out and we'll investigate this.

**Comment by ssrm** [comment]
Any update?

**Comment by yiliuTo** [comment]
Hi @ssrm , the cosmosdb sdk we depend on does not provide the feature that sets TTL on container level and destroys a container according to it. Besides, we think the TTL parameter is usually maintained by the server not the client. 

If you think the feature is necessary then could you share your case and requirement for the reason to set TTL on container level by client?

**Comment by ssrm** [comment]
Hi @yiliuTo ,

Thanks for your reply.

We create containers/documents from java applications. I think most people do this way. We can set document level TTL, but which is applicable only when there is container level TTL set. As per Azure Docs : https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live#time-to-live-for-containers-and-items

By saying Azure Cosmos provides Java SDK to create container with TTL, as per the below doc:

https://docs.microsoft.com/en-us/azure/cosmos-db/migrate-java-v4-sdk?tabs=java-v4-async#container-level-time-to-livettl

**Comment by yiliuTo** [comment]
Hi @ssrm . Please ignore my last comment because I just found that the spring data cosmos repo provides TTL on container level by using the annotation [@Document](https://github.com/microsoft/spring-data-cosmosdb/blob/f62cf3670b54c048599d07ad4b99a51112e4eb52/src/test/java/com/microsoft/azure/spring/data/cosmosdb/domain/TimeToLiveSample.java#L17). Sorry for my mistake and for more detailed information you can refer to the [PR](https://github.com/microsoft/spring-data-cosmosdb/pull/524) and [issue](https://github.com/microsoft/spring-data-cosmosdb/issues/523).

Besides, you mentioned that you'd like to set TTL by _application.properties_, is it a requirement or only a suggestion?

**Comment by ssrm** [comment]
TTL you are mentioning is only on Document (Item) level TTL. But this is not going to be valid until we set container level TTL, while I would like to set in application properties as its going to be read on startup. 

See difference here for container level TTL vs Document level TTL

 https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live#time-to-live-for-containers-and-items

**Comment by ssrm** [comment]
I am using 2.2.4, which didnt pull the fix for some reason, by upgrading to 2.3.1 I did see source code with a fix(need to test). Based on the code what I understand, if document level set it just enables the container level ttl. 

I thought, it would be nice to have thing if we can set TTL via application properties. Not sure, if its already doing it.

**Comment by yiliuTo** [comment]
According to the discussion in this [pr](https://github.com/microsoft/spring-data-cosmosdb/issues/523#issuecomment-638955385), I think @Document can help set TTL on container level. However, currently we don't have the plan to provide another implementation of setting TTL via application.properties since this feature has been satisfied via annotation.

If we are going to provide this feature via application.properties, we will update it here. Thanks for your reporting.
