### ISSUE TITLE
userNameAttribute setting is ignored

### ISSUE THREAD

**Issue by dvut** [microsoft/azure-spring-boot#901]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter (tested with 2.2.4 and 2.2.5-SNAPSHOT)
  
- OS Type: Windows
- Java version: 
  
  - 11
  

## Summary

The user name attribute setting is ignored, the value of the "name" attribute is used instead.

## Reproduce steps

Set the user name attribute in application.properties using:
`spring.security.oauth2.client.provider.azure-oauth-provider.user-name-attribute=upn`
or:
`spring.security.oauth2.client.provider.azure-oauth-provider.userNameAttribute=upn`

Fetch the username as explained in the demo code in this repository:
```java
    @GetMapping("/")
    public String index(Model model, OAuth2AuthenticationToken authentication) {
        model.addAttribute("userName", authentication.getName());
```

## Expected Results

Value of the upn attribute.

## Actual Results

The value of the name attribute is returned.

When setting breakpoints, AADOAuth2UserService.java the userNameAttrName value is null, causing DEFAULT_USERNAME_ATTR_NAME to be returned instead:
```java
    private String getUserNameAttrName(OAuth2UserRequest userRequest) {
        String userNameAttrName = userRequest.getClientRegistration()
                .getProviderDetails().getUserInfoEndpoint().getUserNameAttributeName();
        if (StringUtils.isEmpty(userNameAttrName)) {
            userNameAttrName = DEFAULT_USERNAME_ATTR_NAME;
        }

        return userNameAttrName;
    }
```

**Comment by yiliuTo** [comment]
Hi, @dvut . The `userNameAttribute` value is contained in providers during construction of a client registration. So if you want to set `spring.security.oauth2.client.provider.azure-oauth-provider.user-name-attribute`, then you need to set this as well.

> spring.security.oauth2.client.registration.azure.provider=azure-oauth-provider

Otherwise the default provider `azure` will be chosen which contains the default `userNameAttribute` vaule of "name".

Besides, the attribute `userNameAttribute` cannot be obtained using the API we give in  the sample

```
    @GetMapping("/")
    public String index(Model model, OAuth2AuthenticationToken authentication) {
        model.addAttribute("userName", authentication.getName());
```

`authentication.getName()` is used to obtain the user name, which is different user name attribute.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
