### ISSUE TITLE
[Bug] Key Vault Secrets loaded multiple times

### ISSUE THREAD

**Issue by mrm9084** [microsoft/azure-spring-boot#906]
## Environment

- Spring boot starter:

  azure-keyvault-secrets-spring-boot-starter
  
- OS Type: Windows
- Java version: 
  - 1.8
  

## Summary

 When used with another configuration provider the key vault values are loaded multiple times. I see the values load 4 times, though someone else sees 8.

Initially reported here, https://github.com/Azure/AppConfiguration/issues/306, but seems to be a Key Vault issue.

## Reproduce steps

https://github.com/saragluna/demo-appconfiguration-kv

1. start the application and hit http://localhost:8080
2. wait for a minute
3. Update the value of the config. messages property in app configuration from azure portal.
4. Hit http://localhost:8080 again and the application will refresh the app configuration.
5. While refreshing, I am able to monitor the logs and it fetches the key-vault value azure.cosmosdb.key several time, 8 times to be exact.

## Expected Results

The values are loaded only once.

## Actual Results

The key vault values are loaded multiple times, in large stores this results in a very long startup/refresh times.

**Comment by chenrujun** [comment]
Hi, mrm9084,
(cc @yiliuTo, FYI.)

This is because when app configure refreshes it will trigger out the context refreshing, and key vaults reload as well. It repeats for multiple times is due to we have more than one context. Now it seems our current behavior of app configure refreshing is not reasonable, we will continue looking into it.

**Comment by yiliuTo** [comment]
Hi @mrm9084 , the reason why key vault values load multiple times is as what @chenrujun talked about, it is unavoidable in the process of spring context refreshing. However, we have a [PR](https://github.com/microsoft/azure-spring-boot/pull/905/files) to cache key vault values and then when the environment reads key vault property source, these values are cached locally instead of being requested from the server, which will save the total refresh time.

**Comment by edburns** [comment]
Internally tracked at https://dev.azure.com/azure-spring-integration/spring-integration-private/_workitems/edit/190

**Comment by AbhijeetAvaghade** [comment]
if this part of 2.3.2 release?

**Comment by yiliuTo** [comment]
Hi @AbhijeetAvaghade The associated PR wasn't included in 2.3.2 release, and we plan to release it in 2.3.3 version.
